### ISSUE TITLE
Book errata

### ISSUE THREAD

**Issue by BackSeat** [nuvic/flask_for_startups#5]
Book really helpful, thank you. I found some small issues:

- Page 18: need semicolon on `create user` line
- Likewise on the `grant` line
- Also need `GRANT USAGE, CREATE ON SCHEMA public TO your_user;` (see https://stackoverflow.com/questions/74110708/postgres-15-permission-denied-for-schema-public#answer-74111630)
- Page 28: don't copy the file in `migration/versions`
- Page 28: directory diagram doesn't include `env.py`
- Page 30: "It is tempting to put our functionality in models/serializers since that’s easiest, but writing the functionality in serializers is typically better" - should that be "writing the functionality in services is typically better"?
- Page 31/32: the call to `account_management_services.create_account` doesn't pass the password which that function requires.
- Page 35 - footnote URL 404s (https://ultimatedjango.com/learn-django/lessons/create-stripe-processing-code)
- Page 38 - you use the database name `flask_for_startups` burt earlier it was `your-database-name`. Might be best to use `flask_for_startups` from the beginning.
- Page 52, `account_management_services.py
` listing is missing imports for `AccountValidator` and `custom_errors`
- Code in Kindle really hard to read
- Page 62 `account_management_views.py`: The imports are wrong - some needed are missing (eg, marshmallow) and some included that are not needed (eg, db, User, Account)
- Page 73: I had created more than one user, so the user query failed. Maybe `.first()` instead of `.one()`?
- Page 83, list item 4: missing "db" in "we have a clean by deleting"
- Page 86: not important, but you may want to make the test mail domain be `example.com` which is designed for that use.
- Page 87: semicolon on `psql` line, and also schema permissions as above
- Page 96: contact email incorrect `hi@nuvic.co.`

**Comment by nuvic** [comment]
Thank you very much Keith! I really appreciate the feedback and the kind words. 
I agree with each point, and have updated the book. If you go to the original email from Gumroad, you should be able to see the updated book.
I currently don't have a solution for the kindle issue, but I will continue investigating.
Thank you once again!
